### ISSUE TITLE
A select function to return a field by name

### ISSUE THREAD

**Issue by zhangchiqing** [fantasyland/daggy#11]
Hello,

Does it make sense to provide a `select` function that returns a field by name?

```
const Point3D = daggy.tagged('Point3D', ['x', 'y', 'z'])

// [Point3D]
const points = [
  Point3D(1, 2, 3),
  Point3D(2, 3, 4),
  Point3D(3, 3, 3),
];

// [Number]
const xs = R.map(Point3D.select('x'), points); // [1, 2, 3]

// [Number]
const xs = R.map(Point3D.select('non-exist-field'), points); // TypeError: 'Point3D' doesn't have this field: non-exist-field
```

**Comment by safareli** [comment]
Point3D(1, 2, 3) is normal object, you can just use [`S.prop`](https://sanctuary.js.org/#prop) or [`R.prop`](http://ramdajs.com/docs/#prop)  and many other helpers from there.

**Comment by zhangchiqing** [comment]
Thanks @safareli . Sorry for the late reply.

My original though was that I found myself often write module like this

```js
const Point3D = {
  make: (x, y, z) => { 
    return { x: x, y: y, z: z };
  },
  selectX: (p) => { return p.x; },
  selectY: (p) => { return p.y; },
  selectZ: (p) => { return p.z; },
}
```

So that it will throw exception if I made the following mistakes:
```
R.map(Point3D.selectT, points);
R.map(Point3D.selectX, [undefined]);
```
I'd like to extract the above module definition as a pattern, and I found `daggy.tagged` provides similar functionality, but doesn't have a `select` function to select certain field.

I could do with Sanctuary with the `checkTypes` option on
```
var Point3D = daggy.tagged('Point3D', ['x', 'y', 'z']);
Point3D.select = S.prop;
R.map(Point3D.select('t'), points); // throw
R.map(Point3D.select('x'), [undefined]); // throw
```

Talking about Sanctuary, I like it a lot! And was using it on production. But sometimes, the `checkTypes: true` option causes memory to blow in development, and we have to keep it off. In which case, `Point3D.select = S.prop` basically fallback to `Point3D.select = R.prop` which wouldn't throw exception if I made a typo in the field like this
```
R.map(R.prop('T'), points); 
```

Yes, I could just implement a helper function and select fields like this:
```
var Point3D = daggy.tagged('Point3D', ['x', 'y', 'z']);
...
R.map(helper.select('x'), [Point3D(1, 2, 3)]); // [1]
R.map(helper.select('t'), [Point3D(1,2,3)]); // throw 
R.map(helper.select('t'), [undefined]); // throw 
```
But I'd like `Point3D` to provide the `select` function in order to hide the implementation detail of how to select a field.

So then this is what I end up with:
```
var Point3D = daggy.tagged('Point3D', ['x', 'y', 'z']);
Point3D.select = helper.select;

R.map(Point3D.select('x'), [Point3D(1, 2, 3)]); // [1]
R.map(Point3D.select('t'), [Point3D(1,2,3)]); // throw 
R.map(Point3D.select('t'), [undefined]); // throw 
```

That's why I'm thinking it would be nice if `daggy` just provide such `select` function directly :)

**Comment by safareli** [comment]
You can define something like that on top of daggy

```js
myTagged = (name, props) => {
  const res = daggy.tagged(name,props)
  props.forEach(prop => res[prop] = R.prop(prop))
  return res
}
```

Or you can just write safer version of `R.prop`
```js
const prop = propName => obj => {
  if (!Object.prototype.hasOwnProperty.call(obj,propName)) {throw new TypeError('...')}
  return obj[propName]
}
```


Also adding `selectXXX`functions to constructor will be  problematic for sum types.
