### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by bahmutov** [fantasyland/daggy#13]
Named `taggedSum` from the example is broken (Node 6.9)

```js
const daggy = require('daggy')
const Option = daggy.taggedSum('Option', {
  Some: ['x'],
  None: [],
})
```
```sh
$ node example.js 
/Users/gleb/git/training/node/daggy-maybe/node_modules/daggy/daggy.js:149
            definitions[key] = tagged.apply(null, constructors[key]);
                                      ^

TypeError: CreateListFromArrayLike called on non-object
    at Object.taggedSum (/Users/gleb/git/training/node/daggy-maybe/node_modules/daggy/daggy.js:149:39)
    at Object.<anonymous> (/Users/gleb/git/training/node/daggy-maybe/example.js:2:22)
```
One can skip string `'Option'` but then there are no `Option.Some.is` methods

**Comment by amsross** [comment]
Probably related to https://github.com/fantasyland/daggy/issues/10

**Comment by amsross** [comment]
If you're using the version provided by npm, you'd need to follow the docs there as the current state of the repository and the current version available on npm are not the same (https://www.npmjs.com/package/daggy).

On github you could see them here: https://github.com/fantasyland/daggy/tree/v0.0.1/

**Comment by safareli** [comment]
I think this should be closed now #10 is resolved.
@davidchambers can you close it? (I don't have a permission to close issues)

**Comment by davidchambers** [comment]
> I don't have a permission to close issues

I made you an owner, @safareli. You should now have permission to close issues. :)

**Comment by safareli** [comment]
@davidchambers thanks
