### ISSUE TITLE
Pass prototype object to tagged and taggedSum

### ISSUE THREAD

**Issue by gabejohnson** [fantasyland/daggy#16]
It would be nice to simply pass in an object as the final parameter.
```js
const Point3D = daggy.tagged('Point3D', ['x', 'y', 'z'], {
  scale(n) {
    return Point3D(this.x * n, this.y * n, this.z * n)
  }
})
Point3D.toString() // 'Point3D'
const a = Point3D(1, 2, 3) // { x: 1, y: 2, z: 3 }
a.x == 1 && a.y == 2 && a.z == 3 // true
a.toString() // 'Point3D(1, 2, 3)'
Point3D.is(a) // true
const b = a.scale(2) // { x: 2, y: 4, z: 6 }
b.toString() // 'Point3D(2, 4, 6)'
```
```js
const Option = daggy.taggedSum('Option', {
  Some: ['x'],
  None: [],
}, {
  map(f) {
    return this.cata({
      Some: (x) => Option.Some(f(x)),
      None: () => this,
    })
  }
})
const a = Option.Some(1) // { x: 1 }
a.toString() // 'Option.Some(1)'
Option.Some.is(a) // true
Option.is(a) // true
Option.None.is(Option.None) // true
Option.is(Option.None) // true
Option.None.toString() // 'Option.None'
Option.Some.toString() // 'Option.Some'
const b = a.map(x => x+1) // { x: 2 }
b.toString() // 'Option.Some(2)'
```

It would allow customizing the behavior of `toString`.

**Comment by safareli** [comment]
What you mean by `It would allow customizing the behavior of toString.`
You can customize behavior of toString by mutating `Option.prototype`. 
`toString` which is defined is default implementation which could be changed as you like.

I thought you can mutate `Option.Some.prototype` too but prototype of variants is not exposed.
it could be fixed by adding `typeRep[tag].prototype = tagProto` [here](https://github.com/fantasyland/daggy/blob/master/src/daggy.js#L47-L51).

**Comment by gabejohnson** [comment]
I'm just suggesting this as a convenience. The idea is that if a property is defined on the passed-in proto object, it won't be overridden by `tagged`/`taggedSum`.

I'm doing some work on `sanctuary-tuples` using daggy could cut down on some noise.

```js
var Pair = daggy.tagged('sanctuary-tuples/Pair', ['fst', 'snd'], {
  'fantasy-land/equals': function equals(other) {
    return Z.equals(this.fst, other.fst) && Z.equals(this.snd, other.snd);
  },
  'fantasy-land/bimap': function bimap(f, g) {
    return Pair(f(this.fst), g(this.snd));
  },
  ...
});
Pair['fantasy-land/of'] = function of(a) {
  return Pair(a, a);
};
```

**Comment by safareli** [comment]
Why do you prefer that instead of:

```js
var Pair = daggy.tagged('sanctuary-tuples/Pair', ['fst', 'snd'])

Object.assign(Pair.prototype, {
  'fantasy-land/equals': function equals(other) {
    return Z.equals(this.fst, other.fst) && Z.equals(this.snd, other.snd);
  },
  'fantasy-land/bimap': function bimap(f, g) {
    return Pair(f(this.fst), g(this.snd));
  },
  ...
});

Object.assign(Pair, {
  'fantasy-land/of': function of(a) {
    return Pair(a, a);
  },
  ...
});
```

**Comment by gabejohnson** [comment]
Because it is less to type :smile:. I don't feel strongly, I just figured it was a very small change.

**Comment by safareli** [comment]
I'm concerned about this feature, as one might want to pass an object
- which would be assigned to the result (TypeRep) like for defining `fl.of ` for example.
- which will be used as prototype of resulting objects (one you are proposing)
- for each variant type pass different object which will be assigned to corresponding prototype. (like one for Either.Left.prototype and one for Either.Right.prototype).

it's sort of ambiguous as one might expect different things from the additional argument.

Also I don't thing if it is solving any problem (is it?).

**Comment by gabejohnson** [comment]
The problem it's solving is simply reduced boilerplate. I think things could be disambiguated.

```js
const Option = daggy.taggedSum('Option', {
  of(a) {
    return Option.Some(a);
  }
}, {
  Some: [['x'], {}, {
    map(f) {
      return Option.Some(f(x));
    }
  }],
  None: [[], {}, {
    map() {
      return this;
    }
  }],
});
```

But the added complexity would probably outweigh the benefits.

**Comment by safareli** [comment]
closing this for now
