### ISSUE TITLE
Set up travise

### ISSUE THREAD

**Issue by safareli** [fantasyland/daggy#20]
Currently travis is not set up and test are not executed on PR and commits

**Comment by notgiorgi** [comment]
Also linting setup would be convenient, even some basic setup, like `eslint:recommended`

**Comment by safareli** [comment]
Go for it 🎉

**Comment by notgiorgi** [comment]
Right after another PR gets merged :+1:

**Comment by davidchambers** [comment]
Are you still interested in working on this, @notgiorgi?

**Comment by notgiorgi** [comment]
@davidchambers yep I can do it, totally forgot though :smile: 

which styleguide we should use for eslint?

**Comment by davidchambers** [comment]
> which styleguide we should use for eslint?

We already have `npm run lint` and `npm run test`. We just need to hook these up to Travis. :)

**Comment by notgiorgi** [comment]
Oh, I see, you just merged PR, sorry.

Well then I'll setup `.travise.yml` which runs `check` and `bench` tasks :+1:
