### ISSUE TITLE
Support for older browsers

### ISSUE THREAD

**Issue by eahlberg** [fantasyland/daggy#23]
I've had some troubles using daggy on older browsers (e.g. IE, Safari 8), which I believe is due to the  usage of ES6 features (`const` etc). If I manually transpile the code using a transpiler such as e.g. `babel`, everything works fine.

I'm not very well versed in what the best practices are for publishing `npm` packages, but I'm thinking it might be a good idea to transpile before publishing? See e.g. http://jamesknelson.com/writing-npm-packages-with-es6-using-the-babel-6-cli/

Is this something you've considered?

**Comment by davidchambers** [comment]
In the interest of keeping this project's infrastructure simple, my preference is for daggy's source code to be ES5-compatible. I would support a pull request which makes this a reality.

**Comment by eahlberg** [comment]
ok, cool. I'll look into this tomorrow and see what I can do!
