### ISSUE TITLE
set type based on some exact values

### ISSUE THREAD

**Issue by varenya** [fantasyland/daggy#27]
I am trying to emulate something like this:

https://flow.org/en/docs/types/unions/#toc-disjoint-unions-with-exact-types 

`
const Person = daggy.tagged('Person', ['name', 'age']) 

const DeveloperType = daggy.taggedUnion("DeveloperType" ,{
                     JuniorDeveloper : ['name', {'age' : 26}  ],
                     SeniorDeveloper : ['name' , {'age' , 30}]
})
`

Is this possible already? basically based on specific property value to create mutliple types.

Thanks

**Comment by safareli** [comment]
Purposes of flow is to typecheck existing js code and that feature you linked makes sense to exist for it's purposes.

On the other hand daggy is lib to create ADT's, i.e. new "type" and  "type constructors" which inherit from the "type". therefore the feature you asked is not part of this lib. and in general if a language has ADT's you would solve same problem in different way, like this for example:

``` js
const DeveloperType = daggy.taggedUnion("DeveloperType" ,{
  JuniorDeveloper : ['name'],
  SeniorDeveloper : ['name']
})

// DeveloperType -> Person
toPerson = (d) => d.cata({
  JuniorDeveloper: (n) => Person(n, 26)
  SeniorDeveloper: (n) => Person(n, 30)
}) 
```

or

```
const Responce = daggy.taggedUnion("Responce" ,{
  Success : ['value'],
  Failed : ['message']
})```

**Comment by varenya** [comment]
Yes I understand we can do it this way but its limiting isn't it? you can't do cata on the JuniorDeveloper and Senior Developer.

Right now we are creating ADT's where the distinction is just the variables they store but shouldn't it be possible to create based specific values? Like in this case where they both hold same keys but just differ based on some values.  

I have usecase where in there are bunch of booleans in a object each boolean state represents a sematic business sense which I would like to model as Abstract data type and then based on that type do some logic ( basically doing catamorphism ) which would result in eliminating lot of impossible states for the developer to deal with.

Let me know if I am missing some other way of doing this I am new to this as well :)

**Comment by safareli** [comment]
> Yes I understand we can do it this way but its limiting isn't it? 

As described above this library is not just "cata". the way it's implemented the cata is derived for definition of some type with the type. 

> you can't do cata on the JuniorDeveloper and Senior Developer.

yes because they are not defined using daggy they are just normal objects which are not constracted by daggy. and you don't  need daggy to write "cata" for them:

```
const developerTypeCata = (d,c) => {
  if (d == 26)
    c.Junior(d) 
  else if (d == 30)
    c.Senior(d) 
  else 
   throw "oops"
}
```

**Comment by varenya** [comment]
Thanks! didn't mean to offend in any way I hope my language didn't come across that way.

**Comment by safareli** [comment]
No worries, I'm absolutely not offend or anything :p

**Comment by safareli** [comment]
You are welcome!
