### ISSUE TITLE
Constructors for types with no arguments

### ISSUE THREAD

**Issue by ccorcos** [fantasyland/daggy#5]
I want to get rid of these lines:

https://github.com/puffnfresh/daggy/blob/master/src/daggy.js#L113-L117

Otherwise you can't add a `.map` to Maybe.Nothing.prototype.

**Comment by SimonRichardson** [comment]
I think that breaks quite a few things, so will have to check. You can work
around it by making the object aliases later.

```
const Maybe = extend(maybe, {Nothing, Some})
```

**Comment by anttih** [comment]
I have this same issue. @SimonRichardson is `extend` defined somewhere?

**Comment by SimonRichardson** [comment]
Not that I'm aware of... Was just an idea, maybe it might be worth while adding, although you should add the prototype to the `Maybe` type and not each sum, then use the catamorphism to identify it.

**Comment by safareli** [comment]
Why you need to add value to Nothing? I believe, Nothing is just a value, and if you want to define some method on it you can just define directly
```js
Nothing.map = (f) => Nothing
```

**Comment by SimonRichardson** [comment]
Think this is closed now by @safareli comment. Re-open if you've got questions.
